
from PyQt5 import QtCore, QtGui, QtWidgets

import MySQLdb as mdb

class Ui_MainWindow5(object):

	def LoadInfo(self):
		conn=mdb.connect("localhost","onshop","mysql","onlineshop")
		with conn:
			cur=conn.cursor()
			cur.execute("select d.order_date, o.ord_no,status from Cart d,OrderStatus o,Customers c1 where c1.cus_id=d.cus_id and d.ord_no = o.ord_no and login=1")
			result=cur.fetchall()

		self.od_details.setRowCount(0)
		for row_number,row_data in enumerate(result):
			self.od_details.insertRow(row_number)
			for column_number,data in enumerate(row_data):
				cell=QtWidgets.QTableWidgetItem(str(data))
				cell.setFlags(QtCore.Qt.ItemIsEnabled)
				self.od_details.setItem(row_number,column_number,cell)


	def Loadshipp(self):
		itemindex = self.od_details.currentRow()
		item = self.od_details.item(itemindex,1).text()
		self.orderidline.setText(str(item))
		self.OrdergroupBox.hide()
		self.ShipgroupBox.show()
		self.LoadShipment()

	def Loadfeed(self):
		itemindex = self.od_details.currentRow()
		item = self.od_details.item(itemindex,1).text()
		self.cusfeedpdtid.setText(str(item))
		self.OrdergroupBox.hide()
		self.FeebackgroupBox.show()
		self.whenOpen()

	def LoadData(self):
		conn=mdb.connect("localhost","onshop","mysql","onlineshop")
		with conn:
			odno=self.orderidline.text()
			cur=conn.cursor()
			cur.execute("select tracking, date, ship_add from ShippingDetails s where s.ord_no ="+str(odno))
			results=cur.fetchall()

			for rows in results:
				self.statusline.setText(str(rows[0]))
				self.delivarytimelabel.setText(str(rows[1]))
				self.presentlocationlabel.setText(str(rows[2]))

			stat=self.statusline.text()

			if str(stat)=="Cancelled":
				self.Cancelorderbutton.hide()
			else:
				self.Cancelorderbutton.show()

	def whenOpen(self):
		ordno=self.cusfeedpdtid.text()
		self.textEditgetdesc.setText("")
		self.cusfeedpdtname.setText("")
		conn=mdb.connect("localhost","onshop","mysql","onlineshop")
		with conn:
			cur=conn.cursor()
			cur.execute("select pdt_id from OrderDetails where ord_no = "+str(ordno))
			result=cur.fetchall()

			for row in result:
				id=row[0]
				self.pdtidcomboBox.addItem(str(id))

	def pdtok(self):

		id=self.pdtidcomboBox.currentText()
		conn=mdb.connect("localhost","onshop","mysql","onlineshop")
		with conn:
			cur=conn.cursor()
			cur.execute("select product_name from ProductDetails where pdt_id = "+str(id))
			result=cur.fetchone()[0]
			self.cusfeedpdtname.setText(str(result))

	def enterfeedback(self):
		desc=self.textEditgetdesc.toPlainText()
		rate=self.Ratingslider.value()
		rate=rate+1
		orno=self.cusfeedpdtid.text()
		pdid=self.pdtidcomboBox.currentText()

		conn=mdb.connect("localhost","onshop","mysql","onlineshop")
		with conn:
			cur=conn.cursor()
			cur.execute("select cus_id from Customers where login =1")
			cus=cur.fetchone()[0]

			cur.execute("insert into Feedbacks values("+str(cus)+","+str(pdid)+","+str(rate)+",'"+str(desc)+"')")

		self.FeebackgroupBox.hide()
		self.OrdergroupBox.show()

	def LoadShipment(self):

		self.statusline.setText("")
		self.delivarytimelabel.setText("")
		self.presentlocationlabel.setText("")
		conn=mdb.connect("localhost","onshop","mysql","onlineshop")
		with conn:
			
			odno=self.orderidline.text()
			cur=conn.cursor()
			cur.execute("select tracking, date, ship_add from ShippingDetails s where s.ord_no ="+str(odno))
			results=cur.fetchall()

			for rows in results:
				self.statusline.setText(str(rows[0]))
				self.delivarytimelabel.setText(str(rows[1]))
				self.presentlocationlabel.setText(str(rows[2]))

			stat=self.statusline.text()

			if str(stat)=="Cancelled":
				self.Cancelorderbutton.hide()
			else:
				self.Cancelorderbutton.show()
	
	def LoadCancel(self):
		self.ShipgroupBox.hide()
		self.CancelgroupBox.show()
	
	def goBackord(self):
		self.ShipgroupBox.hide()
		self.OrdergroupBox.show()
		self.LoadInfo()

	def proceedcancel(self):
		issue=self.issuecomboBox.currentText()
		#print(str(issue))
		desc= self.canceldesctextEdit.toPlainText()
		R=self.RRcomboBox.currentText()
		#print(str(R))

		ordno=self.orderidline.text()
		shid="1" #value from shipping.py

		conn=mdb.connect("localhost","onshop","mysql","onlineshop")
		with conn:
			cur=conn.cursor()
			
			cur.execute("update ShippingDetails set tracking='Cancelled' where ord_no ="+str(ordno))
			cur.execute("update OrderStatus set status='Cancelled' where ord_no ="+str(ordno))
			cur.execute("update OrderStatus set reason_for_return = '"+str(issue)+"' where ord_no ="+str(ordno))
			cur.execute("update OrderStatus set cancel_desc = '"+str(desc)+"' where ord_no = "+str(ordno))
			cur.execute("update OrderStatus set ret_or_rep = '"+str(R)+"' where ord_no = "+str(ordno))

		if R=="REPLACE":
			self.replacetext.show()
			self.refundtext.hide()

		if R=="RETURN & REFUND":
			self.refundtext.show()
			self.replacetext.hide()

		self.cancelproceedButton.setEnabled(False)

	def cancelback(self):
		self.ShipgroupBox.show()
		self.CancelgroupBox.hide()
		self.LoadShipment()

	def setupUi(self, MainWindow5):
		MainWindow5.setObjectName("MainWindow5")
		MainWindow5.resize(901, 636)
		self.centralwidget = QtWidgets.QWidget(MainWindow5)
		self.centralwidget.setObjectName("centralwidget")
		self.OrdergroupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.OrdergroupBox.setGeometry(QtCore.QRect(20, 40, 771, 551))
		self.OrdergroupBox.setTitle("")
		self.OrdergroupBox.setObjectName("OrdergroupBox")
		self.od_details = QtWidgets.QTableWidget(self.OrdergroupBox)
		self.od_details.setGeometry(QtCore.QRect(240, 120, 311, 191))
		self.od_details.setFrameShadow(QtWidgets.QFrame.Raised)
		self.od_details.setShowGrid(True)
		self.od_details.setGridStyle(QtCore.Qt.DashLine)
		self.od_details.setObjectName("od_details")
		self.od_details.setColumnCount(3)
		self.od_details.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.od_details.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.od_details.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.od_details.setHorizontalHeaderItem(2, item)
		self.label = QtWidgets.QLabel(self.OrdergroupBox)
		self.label.setGeometry(QtCore.QRect(580, 220, 67, 17))
		self.label.setText("")
		self.label.setObjectName("label")
		self.orderlabel = QtWidgets.QLabel(self.OrdergroupBox)
		self.orderlabel.setGeometry(QtCore.QRect(270, 50, 231, 41))
		font = QtGui.QFont()
		font.setPointSize(18)
		font.setBold(True)
		font.setWeight(75)
		self.orderlabel.setFont(font)
		self.orderlabel.setFrameShape(QtWidgets.QFrame.Box)
		self.orderlabel.setFrameShadow(QtWidgets.QFrame.Raised)
		self.orderlabel.setTextFormat(QtCore.Qt.PlainText)
		self.orderlabel.setAlignment(QtCore.Qt.AlignCenter)
		self.orderlabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.orderlabel.setObjectName("orderlabel")
		self.pushButton_2 = QtWidgets.QPushButton(self.OrdergroupBox)
		self.pushButton_2.setGeometry(QtCore.QRect(140, 360, 111, 31))
		self.pushButton_2.setObjectName("pushButton_2")

		self.pushButton = QtWidgets.QPushButton(self.OrdergroupBox)
		self.pushButton.setGeometry(QtCore.QRect(480, 350, 161, 41))
		self.pushButton.setObjectName("pushButton")

		self.FeebackgroupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.FeebackgroupBox.setGeometry(QtCore.QRect(90, 0, 751, 581))
		self.FeebackgroupBox.setTitle("")
		self.FeebackgroupBox.setObjectName("FeebackgroupBox")

		self.FeebackgroupBox.hide()

		self.desclabel = QtWidgets.QLabel(self.FeebackgroupBox)
		self.desclabel.setGeometry(QtCore.QRect(200, 250, 131, 20))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.desclabel.setFont(font)
		self.desclabel.setObjectName("desclabel")
		self.ratinglabel = QtWidgets.QLabel(self.FeebackgroupBox)
		self.ratinglabel.setGeometry(QtCore.QRect(220, 427, 71, 21))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.ratinglabel.setFont(font)
		self.ratinglabel.setObjectName("ratinglabel")
		self.textEditgetdesc = QtWidgets.QTextEdit(self.FeebackgroupBox)
		self.textEditgetdesc.setGeometry(QtCore.QRect(340, 257, 221, 141))
		self.textEditgetdesc.setInputMethodHints(QtCore.Qt.ImhMultiLine)
		self.textEditgetdesc.setUndoRedoEnabled(False)
		self.textEditgetdesc.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
		self.textEditgetdesc.setLineWrapColumnOrWidth(0)
		self.textEditgetdesc.setTabStopWidth(10)
		self.textEditgetdesc.setObjectName("textEditgetdesc")
		self.label_6 = QtWidgets.QLabel(self.FeebackgroupBox)
		self.label_6.setGeometry(QtCore.QRect(330, 447, 16, 16))
		self.label_6.setAlignment(QtCore.Qt.AlignCenter)
		self.label_6.setObjectName("label_6")
		self.feedbackokbutton = QtWidgets.QPushButton(self.FeebackgroupBox)
		self.feedbackokbutton.setGeometry(QtCore.QRect(440, 477, 89, 25))
		self.feedbackokbutton.setObjectName("feedbackokbutton")

		self.feedbackokbutton.clicked.connect(self.enterfeedback)

		self.label_10 = QtWidgets.QLabel(self.FeebackgroupBox)
		self.label_10.setGeometry(QtCore.QRect(490, 447, 16, 16))
		self.label_10.setAlignment(QtCore.Qt.AlignCenter)
		self.label_10.setObjectName("label_10")
		self.label_2 = QtWidgets.QLabel(self.FeebackgroupBox)
		self.label_2.setGeometry(QtCore.QRect(230, 127, 91, 21))
		self.label_2.setObjectName("label_2")
		self.label_9 = QtWidgets.QLabel(self.FeebackgroupBox)
		self.label_9.setGeometry(QtCore.QRect(450, 447, 16, 16))
		self.label_9.setAlignment(QtCore.Qt.AlignCenter)
		self.label_9.setObjectName("label_9")
		self.cusfeedIdlabel = QtWidgets.QLabel(self.FeebackgroupBox)
		self.cusfeedIdlabel.setGeometry(QtCore.QRect(200, 177, 111, 16))
		self.cusfeedIdlabel.setObjectName("cusfeedIdlabel")
		self.label_8 = QtWidgets.QLabel(self.FeebackgroupBox)
		self.label_8.setGeometry(QtCore.QRect(410, 447, 16, 16))
		self.label_8.setAlignment(QtCore.Qt.AlignCenter)
		self.label_8.setObjectName("label_8")
		self.cusfeednamelabel = QtWidgets.QLabel(self.FeebackgroupBox)
		self.cusfeednamelabel.setGeometry(QtCore.QRect(200, 207, 121, 16))
		self.cusfeednamelabel.setObjectName("cusfeednamelabel")
		self.label_7 = QtWidgets.QLabel(self.FeebackgroupBox)
		self.label_7.setGeometry(QtCore.QRect(370, 447, 16, 16))
		self.label_7.setAlignment(QtCore.Qt.AlignCenter)
		self.label_7.setObjectName("label_7")
		self.Ratingslider = QtWidgets.QSlider(self.FeebackgroupBox)
		self.Ratingslider.setGeometry(QtCore.QRect(330, 427, 171, 19))
		self.Ratingslider.setMaximum(4)
		self.Ratingslider.setSingleStep(1)
		self.Ratingslider.setPageStep(4)
		self.Ratingslider.setProperty("value", 0)
		self.Ratingslider.setSliderPosition(0)
		self.Ratingslider.setOrientation(QtCore.Qt.Horizontal)
		self.Ratingslider.setTickPosition(QtWidgets.QSlider.TicksBelow)
		self.Ratingslider.setTickInterval(1)
		self.Ratingslider.setObjectName("Ratingslider")
		self.cusfeedpdtid = QtWidgets.QLineEdit(self.FeebackgroupBox)
		self.cusfeedpdtid.setGeometry(QtCore.QRect(350, 127, 151, 31))
		self.cusfeedpdtid.setText("")
		self.cusfeedpdtid.setReadOnly(True)
		self.cusfeedpdtid.setClearButtonEnabled(False)
		self.cusfeedpdtid.setObjectName("cusfeedpdtid")
		self.feedbacklabel = QtWidgets.QLabel(self.FeebackgroupBox)
		self.feedbacklabel.setGeometry(QtCore.QRect(270, 67, 171, 61))
		font = QtGui.QFont()
		font.setFamily("Poor Richard")
		font.setPointSize(18)
		font.setBold(True)
		font.setWeight(75)
		self.feedbacklabel.setFont(font)
		self.feedbacklabel.setAlignment(QtCore.Qt.AlignCenter)
		self.feedbacklabel.setObjectName("feedbacklabel")
		self.cusfeedpdtname = QtWidgets.QLineEdit(self.FeebackgroupBox)
		self.cusfeedpdtname.setGeometry(QtCore.QRect(350, 207, 151, 31))
		self.cusfeedpdtname.setText("")
		self.cusfeedpdtname.setReadOnly(True)
		self.cusfeedpdtname.setClearButtonEnabled(False)
		self.cusfeedpdtname.setObjectName("cusfeedpdtname")
		self.pdtidcomboBox = QtWidgets.QComboBox(self.FeebackgroupBox)
		self.pdtidcomboBox.setGeometry(QtCore.QRect(350, 167, 151, 25))
		self.pdtidcomboBox.setObjectName("pdtidcomboBox")
		self.pdtokButton = QtWidgets.QPushButton(self.FeebackgroupBox)
		self.pdtokButton.setGeometry(QtCore.QRect(510, 167, 51, 25))
		self.pdtokButton.setObjectName("pdtokButton")

		self.pdtokButton.clicked.connect(self.pdtok)

		self.ShipgroupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.ShipgroupBox.setGeometry(QtCore.QRect(50, 20, 801, 591))
		self.ShipgroupBox.setTitle("")
		self.ShipgroupBox.setObjectName("ShipgroupBox")

		self.ShipgroupBox.hide()

		self.delivarytimelabel_2 = QtWidgets.QLabel(self.ShipgroupBox)
		self.delivarytimelabel_2.setGeometry(QtCore.QRect(190, 340, 181, 17))
		self.delivarytimelabel_2.setObjectName("delivarytimelabel_2")
		self.orderId = QtWidgets.QLabel(self.ShipgroupBox)
		self.orderId.setGeometry(QtCore.QRect(190, 210, 67, 17))
		self.orderId.setObjectName("orderId")
		self.presentlocationlabel = QtWidgets.QLineEdit(self.ShipgroupBox)
		self.presentlocationlabel.setGeometry(QtCore.QRect(410, 290, 201, 25))
		self.presentlocationlabel.setReadOnly(True)
		self.presentlocationlabel.setObjectName("presentlocationlabel")
		self.statusline = QtWidgets.QLineEdit(self.ShipgroupBox)
		self.statusline.setGeometry(QtCore.QRect(410, 250, 201, 25))
		self.statusline.setReadOnly(True)
		self.statusline.setObjectName("statusline")
		self.delivarytimelabel = QtWidgets.QLineEdit(self.ShipgroupBox)
		self.delivarytimelabel.setGeometry(QtCore.QRect(410, 330, 201, 25))
		self.delivarytimelabel.setReadOnly(True)
		self.delivarytimelabel.setObjectName("delivarytimelabel")
		self.gobacktoorder = QtWidgets.QPushButton(self.ShipgroupBox)
		self.gobacktoorder.setGeometry(QtCore.QRect(190, 410, 91, 23))
		self.gobacktoorder.setObjectName("gobacktoorder")

		self.gobacktoorder.clicked.connect(self.goBackord)

		self.orderidline = QtWidgets.QLineEdit(self.ShipgroupBox)
		self.orderidline.setGeometry(QtCore.QRect(410, 200, 201, 25))
		self.orderidline.setText("")
		self.orderidline.setReadOnly(True)
		self.orderidline.setClearButtonEnabled(False)
		self.orderidline.setObjectName("orderidline")
		self.label_3 = QtWidgets.QLabel(self.ShipgroupBox)
		self.label_3.setGeometry(QtCore.QRect(290, 80, 221, 71))
		font = QtGui.QFont()
		font.setPointSize(18)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.label_3.setFont(font)
		self.label_3.setFrameShape(QtWidgets.QFrame.Box)
		self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
		self.label_3.setObjectName("label_3")
		self.label_4 = QtWidgets.QLabel(self.ShipgroupBox)
		self.label_4.setGeometry(QtCore.QRect(190, 250, 67, 17))
		self.label_4.setObjectName("label_4")
		self.presentlocationlabel_2 = QtWidgets.QLabel(self.ShipgroupBox)
		self.presentlocationlabel_2.setGeometry(QtCore.QRect(190, 300, 141, 17))
		self.presentlocationlabel_2.setObjectName("presentlocationlabel_2")
		self.Cancelorderbutton = QtWidgets.QPushButton(self.ShipgroupBox)
		self.Cancelorderbutton.setGeometry(QtCore.QRect(520, 410, 101, 25))
		self.Cancelorderbutton.setObjectName("Cancelorderbutton")
		self.CancelgroupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.CancelgroupBox.setGeometry(QtCore.QRect(20, 20, 731, 521))
		self.CancelgroupBox.setTitle("")
		self.CancelgroupBox.setObjectName("CancelgroupBox")

		self.CancelgroupBox.hide()

		self.issuecomboBox = QtWidgets.QComboBox(self.CancelgroupBox)
		self.issuecomboBox.setGeometry(QtCore.QRect(410, 170, 211, 22))
		self.issuecomboBox.setObjectName("issuecomboBox")
		self.issuecomboBox.addItem("")
		self.issuecomboBox.addItem("")
		self.issuecomboBox.addItem("")
		self.issuecomboBox.addItem("")
		self.issuecomboBox.addItem("")
		self.issuecomboBox.addItem("")
		self.Cancellabel = QtWidgets.QLabel(self.CancelgroupBox)
		self.Cancellabel.setGeometry(QtCore.QRect(270, 80, 271, 61))
		font = QtGui.QFont()
		font.setFamily("Narkisim")
		font.setPointSize(18)
		self.Cancellabel.setFont(font)
		self.Cancellabel.setFrameShape(QtWidgets.QFrame.Box)
		self.Cancellabel.setAlignment(QtCore.Qt.AlignCenter)
		self.Cancellabel.setObjectName("Cancellabel")
		self.issuelabel = QtWidgets.QLabel(self.CancelgroupBox)
		self.issuelabel.setGeometry(QtCore.QRect(210, 170, 141, 21))
		font = QtGui.QFont()
		font.setFamily("Narkisim")
		font.setPointSize(10)
		self.issuelabel.setFont(font)
		self.issuelabel.setObjectName("issuelabel")
		self.canceldesctextEdit = QtWidgets.QTextEdit(self.CancelgroupBox)
		self.canceldesctextEdit.setGeometry(QtCore.QRect(410, 210, 211, 81))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(250)
		sizePolicy.setHeightForWidth(self.canceldesctextEdit.sizePolicy().hasHeightForWidth())
		self.canceldesctextEdit.setSizePolicy(sizePolicy)
		self.canceldesctextEdit.setFrameShape(QtWidgets.QFrame.Box)
		self.canceldesctextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
		self.canceldesctextEdit.setReadOnly(False)
		self.canceldesctextEdit.setObjectName("canceldesctextEdit")
		self.cancelbackButton = QtWidgets.QPushButton(self.CancelgroupBox)
		self.cancelbackButton.setGeometry(QtCore.QRect(200, 430, 91, 23))
		self.cancelbackButton.setObjectName("cancelbackButton")
		self.replacetext = QtWidgets.QPlainTextEdit(self.CancelgroupBox)
		self.replacetext.setGeometry(QtCore.QRect(170, 370, 511, 51))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.replacetext.setFont(font)
		self.replacetext.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.replacetext.setFrameShadow(QtWidgets.QFrame.Plain)
		self.replacetext.setReadOnly(True)
		self.replacetext.setCenterOnScroll(False)
		self.replacetext.setObjectName("replacetext")

		self.replacetext.hide()

		self.cancelproceedButton = QtWidgets.QPushButton(self.CancelgroupBox)
		self.cancelproceedButton.setGeometry(QtCore.QRect(490, 430, 181, 23))
		self.cancelproceedButton.setObjectName("cancelproceedButton")
		self.RRlabel = QtWidgets.QLabel(self.CancelgroupBox)
		self.RRlabel.setGeometry(QtCore.QRect(210, 310, 171, 21))
		font = QtGui.QFont()
		font.setFamily("Narkisim")
		font.setPointSize(10)
		self.RRlabel.setFont(font)
		self.RRlabel.setObjectName("RRlabel")
		self.RRcomboBox = QtWidgets.QComboBox(self.CancelgroupBox)
		self.RRcomboBox.setGeometry(QtCore.QRect(410, 310, 211, 22))
		self.RRcomboBox.setObjectName("RRcomboBox")
		self.RRcomboBox.addItem("")
		self.RRcomboBox.addItem("")
		self.canceldesclabel = QtWidgets.QLabel(self.CancelgroupBox)
		self.canceldesclabel.setGeometry(QtCore.QRect(210, 210, 121, 21))
		font = QtGui.QFont()
		font.setFamily("Narkisim")
		font.setPointSize(11)
		self.canceldesclabel.setFont(font)
		self.canceldesclabel.setObjectName("canceldesclabel")
		self.refundtext = QtWidgets.QPlainTextEdit(self.CancelgroupBox)
		self.refundtext.setGeometry(QtCore.QRect(160, 340, 531, 71))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.refundtext.setFont(font)
		self.refundtext.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.refundtext.setFrameShadow(QtWidgets.QFrame.Plain)
		self.refundtext.setReadOnly(True)
		self.refundtext.setCenterOnScroll(False)
		self.refundtext.setObjectName("refundtext")

		self.refundtext.hide()

		MainWindow5.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow5)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 22))
		self.menubar.setObjectName("menubar")
		MainWindow5.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow5)
		self.statusbar.setObjectName("statusbar")
		MainWindow5.setStatusBar(self.statusbar)

		self.LoadInfo()
		self.pushButton_2.clicked.connect(self.Loadfeed)
		self.pushButton.clicked.connect(self.Loadshipp)

		self.Cancelorderbutton.hide()
		self.Cancelorderbutton.clicked.connect(self.LoadCancel)

		self.cancelbackButton.clicked.connect(self.cancelback)
		self.cancelproceedButton.clicked.connect(self.proceedcancel)

		self.retranslateUi(MainWindow5)
		QtCore.QMetaObject.connectSlotsByName(MainWindow5)

	def retranslateUi(self, MainWindow5):
		_translate = QtCore.QCoreApplication.translate
		MainWindow5.setWindowTitle(_translate("MainWindow5", "MainWindow"))
		self.od_details.setSortingEnabled(False)
		item = self.od_details.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow5", "Date"))
		item = self.od_details.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow5", "Order ID"))
		item = self.od_details.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow5", "Status"))
		self.orderlabel.setText(_translate("MainWindow5", "YOUR ORDERS"))
		self.pushButton_2.setText(_translate("MainWindow5", "FEED BACK"))
		self.pushButton.setText(_translate("MainWindow5", "SHIPPING DETAILS"))
		self.desclabel.setText(_translate("MainWindow5", "DESCRIPTION :"))
		self.ratinglabel.setText(_translate("MainWindow5", "RATING"))
		self.label_6.setText(_translate("MainWindow5", "1"))
		self.feedbackokbutton.setText(_translate("MainWindow5", "OK"))
		self.label_10.setText(_translate("MainWindow5", "5"))
		self.label_2.setText(_translate("MainWindow5", "ORDER ID"))
		self.label_9.setText(_translate("MainWindow5", "4"))
		self.cusfeedIdlabel.setText(_translate("MainWindow5", "PRODUCT-ID"))
		self.label_8.setText(_translate("MainWindow5", "3"))
		self.cusfeednamelabel.setText(_translate("MainWindow5", "PRODUCT NAME"))
		self.label_7.setText(_translate("MainWindow5", "2"))
		self.feedbacklabel.setText(_translate("MainWindow5", "FEED BACK"))
		self.pdtokButton.setText(_translate("MainWindow5", "OK"))
		self.delivarytimelabel_2.setText(_translate("MainWindow5", "Shipment Date:"))
		self.orderId.setText(_translate("MainWindow5", "Order Id :"))
		self.gobacktoorder.setText(_translate("MainWindow5", "Go Back"))
		self.label_3.setText(_translate("MainWindow5", "Shipment Details"))
		self.label_4.setText(_translate("MainWindow5", "Status     :"))
		self.presentlocationlabel_2.setText(_translate("MainWindow5", "Shipment Address:"))
		self.Cancelorderbutton.setText(_translate("MainWindow5", "Cancel Order"))
		self.issuecomboBox.setItemText(0, _translate("MainWindow5", "ORDERED BY MISTAKE"))
		self.issuecomboBox.setItemText(1, _translate("MainWindow5", "PRODUCT IS DAMAGED"))
		self.issuecomboBox.setItemText(2, _translate("MainWindow5", "PRODUCT IS MISSING"))
		self.issuecomboBox.setItemText(3, _translate("MainWindow5", "ITEM NOT MATCHING"))
		self.issuecomboBox.setItemText(4, _translate("MainWindow5", "RECEIVED A DIFFERENT PRODUCT"))
		self.issuecomboBox.setItemText(5, _translate("MainWindow5", "MY  REASON NOT MENTIONED"))
		self.Cancellabel.setText(_translate("MainWindow5", "CANCELLATION"))
		self.issuelabel.setText(_translate("MainWindow5", "ISSUE WITH THE ITEM :"))
		self.cancelbackButton.setText(_translate("MainWindow5", "GO BACK"))
		self.replacetext.setPlainText(_translate("MainWindow5", "We apologise for any inconvinience.\n"
"Your request for replacing the product is accepted."))
		self.cancelproceedButton.setText(_translate("MainWindow5", "PROCEED TO CANCEL"))
		self.RRlabel.setText(_translate("MainWindow5", "WHAT DO YOU WANT : "))
		self.RRcomboBox.setItemText(0, _translate("MainWindow5", "REPLACE"))
		self.RRcomboBox.setItemText(1, _translate("MainWindow5", "RETURN & REFUND"))
		self.canceldesclabel.setText(_translate("MainWindow5", "DESCRIBE :"))
		self.refundtext.setPlainText(_translate("MainWindow5", "We apologise for any inconvinience.\n"
"Your request for returning the product has been accepted.\n"
"Money will be credited in your bank account."))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow5 = QtWidgets.QMainWindow()
	ui = Ui_MainWindow5()
	ui.setupUi(MainWindow5)
	MainWindow5.show()
	sys.exit(app.exec_())

