
from PyQt5 import QtCore, QtGui, QtWidgets

import MySQLdb as mdb

class Ui_MainWindow(object):

	def Check(self):
		card=self.Pay_lineEdit_4.text()
		exp=self.dateEdit.text()
		cv=self.Pay_lineEdit_6.text()
		
		now=datetime.date.today()
		if len(card)<16:
			self.Pay_label_10.setText("Invalid Card No")

		#elif str(exp)<str(now):
			
			#self.Pay_label_10.setText("Expired Card")

		elif len(cv)<3:
			self.Pay_label_10.setText("Incorrect CVV")
		else:
			self.Pay_label_10.setText("Success")
		


	def LoadTable(self):
		conn=mdb.connect("localhost", "onshop", "mysql", "onlineshop")
		with conn:
			cur=conn.cursor()
			cur.execute("select cus_id from Customers where login=1")
			result=cur.fetchone()[0]
			cur.execute("select c.ord_no, pdt_id, qty from OrderDetails o,Cart c where o.ord_no = c.ord_no and cus_id ="+str(result))
			result=cur.fetchall()
			self.Pay_tableWidget_2.setRowCount(0)
			for row_number,row_data in enumerate (result):
				self.Pay_tableWidget_2.insertRow(row_number)
				for column_number,data in enumerate(row_data):
					self.Pay_tableWidget_2.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
			
			cur.close()
	def LoadData(self):
		
		conn=mdb.connect("localhost", "onshop", "mysql", "onlineshop")
		with conn:
			cur=conn.cursor()
			
			ord= self.Pay_lineEdit.text()
			if str(ord)=="":
				self.Pay_label_2.setText("Pls Enter the order no.")
			else:
				cur.execute("select * from OrderDetails where ord_no="+ord+"")
				count=cur.rowcount
				if count==0:
					self.Pay_label_2.setText("OrderNo does not exist")
				
				else:
					self.Pay_groupBox.setEnabled(True)
					#cur.execute('select p.price*o.qty from ProductDetails p,OrderDetails o where o.pdt_id=p.pdt_id and o.ord_no="'+str(ord)+'"')
					
					cur.execute('create view amt as (select p.price*o.qty as pr from ProductDetails p,OrderDetails o where o.pdt_id=p.pdt_id and o.ord_no='+str(ord)+')')
					cur.execute("select sum(pr) from amt")

					result=cur.fetchone()[0]
					cur.execute("drop view amt")
					###############################################################
					if self.Pay_radioButton_2.isChecked()==True:
						
						insert_stm = (
					"INSERT INTO PaymentDetails (ord_no,price,mode,payment_date) "
					"VALUES (%s, %s, %s,%s)"
					)
						dataa = (str(ord), str(result),"card","2019-04-13")
						cur.execute(insert_stm, dataa)
					if self.Pay_radioButton.isChecked()==True:
						
						insert_stm = (
					"INSERT INTO PaymentDetails (ord_no,price,mode,payment_date) "
					"VALUES (%s, %s, %s,%s)"
					)
						dataa = (str(ord), str(result),"COD","2019-04-13")
						cur.execute(insert_stm, dataa)
						cur.execute('select max(pay_id) from PaymentDetails ')
						r=cur.fetchone()[0]
						self.Pay_label_2.setText(str(r))
					
					#cur.execute("insert into PaymentDetails ")
					self.Pay_label_12.setText(str(result))
					self.Pay_label_2.setText("  ")
					cur.close()


	def ButtonState(self):
		if self.Pay_radioButton.isChecked() ==True:
			self.Pay_groupBox_2.setEnabled(False)
			#self.LoadData()
			#self.groupBox_2.setEnabled(True)
		if self.Pay_radioButton_2.isChecked()==True:
			#self.groupBox_2.setEnabled(False)
			self.Pay_groupBox_2.setEnabled(True)

	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1022, 704)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.Pay_groupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.Pay_groupBox.setGeometry(QtCore.QRect(370, 110, 611, 461))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.Pay_groupBox.setFont(font)
		self.Pay_groupBox.setStyleSheet("")
		self.Pay_groupBox.setTitle("")
		self.Pay_groupBox.setObjectName("Pay_groupBox")

		self.Pay_groupBox.setEnabled(False)

		self.Pay_label_3 = QtWidgets.QLabel(self.Pay_groupBox)
		self.Pay_label_3.setGeometry(QtCore.QRect(60, 60, 161, 20))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_3.setFont(font)
		self.Pay_label_3.setStyleSheet("")
		self.Pay_label_3.setObjectName("Pay_label_3")
		self.Pay_radioButton_2 = QtWidgets.QRadioButton(self.Pay_groupBox)
		self.Pay_radioButton_2.setGeometry(QtCore.QRect(340, 170, 211, 26))

		self.Pay_radioButton_2.clicked.connect(self.ButtonState)

		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_radioButton_2.setFont(font)
		self.Pay_radioButton_2.setStyleSheet("")
		self.Pay_radioButton_2.setObjectName("Pay_radioButton_2")
		self.Pay_label_4 = QtWidgets.QLabel(self.Pay_groupBox)
		self.Pay_label_4.setGeometry(QtCore.QRect(60, 120, 181, 20))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_4.setFont(font)
		self.Pay_label_4.setStyleSheet("")
		self.Pay_label_4.setObjectName("Pay_label_4")
		self.Pay_radioButton = QtWidgets.QRadioButton(self.Pay_groupBox)
		self.Pay_radioButton.setGeometry(QtCore.QRect(50, 170, 201, 26))

		self.Pay_radioButton.clicked.connect(self.ButtonState)

		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_radioButton.setFont(font)
		self.Pay_radioButton.setStyleSheet("")
		self.Pay_radioButton.setObjectName("Pay_radioButton")
		self.Pay_groupBox_2 = QtWidgets.QGroupBox(self.Pay_groupBox)
		self.Pay_groupBox_2.setGeometry(QtCore.QRect(260, 200, 331, 251))
		self.Pay_groupBox_2.setStyleSheet("QGroup\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(196, 160, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
		self.Pay_groupBox_2.setTitle("")
		self.Pay_groupBox_2.setObjectName("Pay_groupBox_2")

		self.Pay_groupBox_2.setEnabled(False)

		self.Pay_frame_2 = QtWidgets.QFrame(self.Pay_groupBox_2)
		self.Pay_frame_2.setGeometry(QtCore.QRect(30, 40, 281, 201))
		self.Pay_frame_2.setStyleSheet("")
		self.Pay_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.Pay_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
		self.Pay_frame_2.setObjectName("Pay_frame_2")
		self.Pay_label_5 = QtWidgets.QLabel(self.Pay_frame_2)
		self.Pay_label_5.setGeometry(QtCore.QRect(20, 40, 131, 20))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_5.setFont(font)
		self.Pay_label_5.setStyleSheet("")
		self.Pay_label_5.setObjectName("Pay_label_5")
		self.Pay_label_6 = QtWidgets.QLabel(self.Pay_frame_2)
		self.Pay_label_6.setGeometry(QtCore.QRect(20, 70, 131, 20))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_6.setFont(font)
		self.Pay_label_6.setStyleSheet("")
		self.Pay_label_6.setObjectName("Pay_label_6")
		self.Pay_label_7 = QtWidgets.QLabel(self.Pay_frame_2)
		self.Pay_label_7.setGeometry(QtCore.QRect(20, 100, 62, 20))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_7.setFont(font)
		self.Pay_label_7.setStyleSheet("")
		self.Pay_label_7.setObjectName("Pay_label_7")
		self.Pay_lineEdit_4 = QtWidgets.QLineEdit(self.Pay_frame_2)
		self.Pay_lineEdit_4.setGeometry(QtCore.QRect(160, 40, 113, 28))
		self.Pay_lineEdit_4.setStyleSheet("")
		self.Pay_lineEdit_4.setObjectName("Pay_lineEdit_4")

		self.Pay_lineEdit_4.setMaxLength(16)

		self.Pay_lineEdit_6 = QtWidgets.QLineEdit(self.Pay_frame_2)
		self.Pay_lineEdit_6.setGeometry(QtCore.QRect(160, 100, 113, 28))
		self.Pay_lineEdit_6.setStyleSheet("")
		self.Pay_lineEdit_6.setObjectName("Pay_lineEdit_6")

		self.Pay_lineEdit_6.setMaxLength(3)

		self.Pay_pushButton = QtWidgets.QPushButton(self.Pay_frame_2)
		self.Pay_pushButton.setGeometry(QtCore.QRect(60, 160, 171, 28))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_pushButton.setFont(font)
		self.Pay_pushButton.setStyleSheet("")
		self.Pay_pushButton.setObjectName("Pay_pushButton")

		self.Pay_pushButton.clicked.connect(self.Check)

		self.Pay_label_10 = QtWidgets.QLabel(self.Pay_frame_2)
		self.Pay_label_10.setGeometry(QtCore.QRect(80, 130, 131, 21))
		self.Pay_label_10.setStyleSheet("")
		self.Pay_label_10.setText("")
		self.Pay_label_10.setObjectName("Pay_label_10")
		self.dateEdit = QtWidgets.QDateEdit(self.Pay_frame_2)
		self.dateEdit.setGeometry(QtCore.QRect(160, 70, 110, 29))
		self.dateEdit.setStyleSheet("")
		self.dateEdit.setObjectName("dateEdit")
		self.Pay_label_12 = QtWidgets.QLabel(self.Pay_groupBox)
		self.Pay_label_12.setGeometry(QtCore.QRect(260, 50, 91, 31))
		font = QtGui.QFont()
		font.setFamily("Waree")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_12.setFont(font)
		self.Pay_label_12.setStyleSheet("")
		self.Pay_label_12.setObjectName("Pay_label_12")
		self.Pay_pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
		self.Pay_pushButton_6.setGeometry(QtCore.QRect(920, 750, 89, 31))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.Pay_pushButton_6.setFont(font)
		self.Pay_pushButton_6.setStyleSheet("")
		self.Pay_pushButton_6.setObjectName("Pay_pushButton_6")
		self.Pay_pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
		self.Pay_pushButton_2.setGeometry(QtCore.QRect(120, 380, 89, 31))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.Pay_pushButton_2.setFont(font)
		self.Pay_pushButton_2.setStyleSheet("")
		self.Pay_pushButton_2.setObjectName("Pay_pushButton_2")

		self.Pay_pushButton_2.clicked.connect(self.LoadTable)

		self.Pay_tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
		self.Pay_tableWidget_2.setGeometry(QtCore.QRect(10, 170, 321, 201))
		self.Pay_tableWidget_2.setStyleSheet("")
		self.Pay_tableWidget_2.setRowCount(5)
		self.Pay_tableWidget_2.setColumnCount(6)
		self.Pay_tableWidget_2.setObjectName("Pay_tableWidget_2")
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		item.setFont(font)
		self.Pay_tableWidget_2.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		item.setFont(font)
		self.Pay_tableWidget_2.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		item.setFont(font)
		self.Pay_tableWidget_2.setHorizontalHeaderItem(2, item)
		self.Pay_frame_3 = QtWidgets.QFrame(self.centralwidget)
		self.Pay_frame_3.setGeometry(QtCore.QRect(20, 410, 311, 161))
		self.Pay_frame_3.setStyleSheet("")
		self.Pay_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.Pay_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
		self.Pay_frame_3.setObjectName("Pay_frame_3")
		self.Pay_label = QtWidgets.QLabel(self.Pay_frame_3)
		self.Pay_label.setGeometry(QtCore.QRect(20, 20, 141, 20))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label.setFont(font)
		self.Pay_label.setStyleSheet("")
		self.Pay_label.setObjectName("Pay_label")
		self.Pay_lineEdit = QtWidgets.QLineEdit(self.Pay_frame_3)
		self.Pay_lineEdit.setGeometry(QtCore.QRect(180, 20, 113, 28))
		self.Pay_lineEdit.setStyleSheet("")
		self.Pay_lineEdit.setObjectName("Pay_lineEdit")
		self.Pay_pushButton_4 = QtWidgets.QPushButton(self.Pay_frame_3)
		self.Pay_pushButton_4.setGeometry(QtCore.QRect(90, 100, 89, 31))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.Pay_pushButton_4.setFont(font)
		self.Pay_pushButton_4.setStyleSheet("")
		self.Pay_pushButton_4.setObjectName("Pay_pushButton_4")

		self.Pay_pushButton_4.clicked.connect(self.LoadData)

		self.Pay_label_2 = QtWidgets.QLabel(self.Pay_frame_3)
		self.Pay_label_2.setGeometry(QtCore.QRect(80, 60, 221, 21))
		font = QtGui.QFont()
		font.setFamily("Waree")
		font.setPointSize(13)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_2.setFont(font)
		self.Pay_label_2.setStyleSheet("")
		self.Pay_label_2.setText("")
		self.Pay_label_2.setObjectName("Pay_label_2")
		self.Pay_label_9 = QtWidgets.QLabel(self.centralwidget)
		self.Pay_label_9.setGeometry(QtCore.QRect(10, 130, 191, 31))
		font = QtGui.QFont()
		font.setFamily("DejaVu Serif")
		font.setPointSize(24)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_9.setFont(font)
		self.Pay_label_9.setStyleSheet("")
		self.Pay_label_9.setObjectName("Pay_label_9")
		# self.Pay_pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
		# self.Pay_pushButton_5.setGeometry(QtCore.QRect(40, 40, 71, 21))
		# font = QtGui.QFont()
		# font.setFamily("URW Bookman L")
		# font.setPointSize(14)
		# font.setBold(True)
		# font.setItalic(False)
		# font.setWeight(75)
		# self.Pay_pushButton_5.setFont(font)
		# self.Pay_pushButton_5.setStyleSheet("")
		# self.Pay_pushButton_5.setObjectName("Pay_pushButton_5")
		self.Pay_label_8 = QtWidgets.QLabel(self.centralwidget)
		self.Pay_label_8.setGeometry(QtCore.QRect(350, 20, 231, 51))
		font = QtGui.QFont()
		font.setFamily("DejaVu Serif")
		font.setPointSize(24)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.Pay_label_8.setFont(font)
		self.Pay_label_8.setStyleSheet("")
		self.Pay_label_8.setObjectName("Pay_label_8")
		self.Pay_pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
		self.Pay_pushButton_7.setGeometry(QtCore.QRect(760, 600, 89, 31))
		font = QtGui.QFont()
		font.setFamily("URW Bookman L")
		font.setPointSize(14)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.Pay_pushButton_7.setFont(font)
		self.Pay_pushButton_7.setStyleSheet("")
		self.Pay_pushButton_7.setObjectName("Pay_pushButton_7")

		self.Pay_pushButton_7.clicked.connect(self.LoadData)

		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 22))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.Pay_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Total Amount</span></p></body></html>"))
		self.Pay_radioButton_2.setText(_translate("MainWindow", "Debit/Credit Card"))
		self.Pay_label_4.setText(_translate("MainWindow", "Mode Of Payment"))
		self.Pay_radioButton.setText(_translate("MainWindow", "Cash On Delivery"))
		self.Pay_label_5.setText(_translate("MainWindow", "Card Number"))
		self.Pay_label_6.setText(_translate("MainWindow", "Expiry Date"))
		self.Pay_label_7.setText(_translate("MainWindow", "CVV"))
		self.Pay_pushButton.setText(_translate("MainWindow", "Make Payment"))
		self.Pay_label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
		self.Pay_pushButton_6.setText(_translate("MainWindow", "Next"))
		self.Pay_pushButton_2.setText(_translate("MainWindow", "Load"))
		item = self.Pay_tableWidget_2.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "OrderNo"))
		item = self.Pay_tableWidget_2.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "ProductID"))
		item = self.Pay_tableWidget_2.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "Quantity"))
		self.Pay_label.setText(_translate("MainWindow", "Order Number"))
		self.Pay_pushButton_4.setText(_translate("MainWindow", "Buy Now"))
		self.Pay_label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Your Orders:</span></p></body></html>"))
		#self.Pay_pushButton_5.setText(_translate("MainWindow", "Back"))
		self.Pay_label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">PAYMENT</span></p></body></html>"))
		self.Pay_pushButton_7.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

